### ISSUE TITLE
How to change hyperparameters in subsequent runs?

### ISSUE THREAD

**Issue by hollowgalaxy** [keras-team/keras-tuner#149]
Given a starting code that looks something like this...
```
hp = HyperParameters()
hp.Choice('learning_rate', values=[1., 1e-1, 1e-2, 1e-3])
tuner = BayesianOptimization(build_model, objective='val_loss', hyperparameters=hp, tune_new_entries=True, max_trials=10, ...)
tuner.search(...)
```
But after running it, I realized I wanted to include two more values `1e-4` and `1e-5`. 
I increase the number of max trials to 12 include these in the search space. Should I do.
```
hp.Choice('learning_rate', values=[1e-4, 1e-5])
```
Although, this didn't work, the old hp values were used for any new trials.

**OR** is this the better approach
```
hp.Choice('learning_rate', values=[1., 1e-1, 1e-2, 1e-3, 1e-4, 1e-5])
```
Also not sure if this worked, the old hp values were used for new trials, and bayasian may have excluded them on purpose.

**Just tested**: after acquiring the `tuner`, `tuner.search_space_summary()` returned the old values for both approaches.

**Comment by omalleyt12** [comment]
@hollowgalaxy Thanks for the issue!

If you want to overwrite an existing project, you can pass `overwrite=True` to the `Tuner`. Otherwise the previous project's settings will be used, which right now includes the old HyperParameters.

There might be a way for us to not reload the old hyperparameters, and/or to prefer explicitly passed new hyperparameter spaces. I'm not sure what is best, as changing the hyperparameter space will break, for instance, BayesianOptimization in many cases
