### ISSUE TITLE
Tune  ReduceLROnPlateau Callback?

### ISSUE THREAD

**Issue by hollowgalaxy** [keras-team/keras-tuner#150]
Noticed that currently the callbacks get copied.
https://github.com/keras-team/keras-tuner/blob/4e48da162ec97fc70d5bf880eedf2d73d1be8a2c/kerastuner/engine/tuner.py#L126

 Primarily, I wanted to use this to tune ReduceLROnPlateau for both patience and delta. 

Not sure what the best solution for this, perhaps a build_callbacks function
such as
```
if self.build_callbacks is None:
    callbacks = fit_kwargs.pop('callbacks', [])
    callbacks = self._deepcopy_callbacks(callbacks)
else:
   callbacks = self.build_callbacks(trial.hyperparameters)

callbacks.append(tuner_utils.TunerCallback(self, trial))
```

**Comment by omalleyt12** [comment]
@hollowgalaxy Thanks for the issue!

I'd recommend subclassing the Tuner and creating the callback inside the Tuner for this use case:

```python
class MyTuner(kt.Tuner):
  def run_trial(trial, *args, **kwargs):
    patience = hp.Int('patience', 0, 3, default=1)
    callbacks = tf.keras.callbacks.ReduceLROnPlateau(patience=patience)
    super(MyTuner, self).run_trial(*args, **kwargs, callbacks=callbacks)
```

In general I think overriding `run_trial` should be the recommended way to do most things that can't be done through having a custom `build_model` (rather than having special methods for other use cases). This way we can keep things as flexible as possible, with `build_model` really just being a convenience function for the most common use case
