### ISSUE TITLE
RandomSearch hyperparameter space contains impossible combinations

### ISSUE THREAD

**Issue by bhnn** [keras-team/keras-tuner#228]
My build_model() method iteratively constructs models with different amounts of dense layers, like this:

```
dense_sizes = [64, 128, 256]
for layer in range(params.Int('num_layer', min_value=1, max_value=4)):
  net = layers.Dense(params.Choice(f'size_layer_L{layer}', dense_sizes), ...)(net)
  net = layers.Dropout(0.5)(net)
```

During runtime, the trial summaries will show something like this:
```
> Hyperparameters:
|-size_layer_L0: 256
|-size_layer_L1: 256
|-size_layer_L2: 256
|-num_layers: 2
```
Given the fact that only 2 layers were constructed iteratively, how can there be hyperparameters for 3 layers? There are several trial summary entries like this.

When the tuner's output regarding best hyperparameters tells me something like this, how should I interpret it? Does `RandomSearch `just instantiate all parameters randomly, even if they are not used in this run?

**Comment by yogi-dmt** [comment]
Yea I believe it does however your model will only use the appropriate gps.
You can verify by printing the model summary.

If you are concerned about collisions and the tuner essentially testing the
same configuration multiple times I made a few tweaks so that the tuner
creates hashes appropriately. Ie. If your model only had 2 layers. Layer 3
params wont be used in the hashes. It basically involves building the model
before every hash and keeping track of which params are actually pulled
from during this process. Might not be the best way but it seems to work.

**Comment by basso95** [comment]
I am experiencing the same problem, has there been any official solution to this problem?
So even though in the summary are printed more layers, not all of them are used?

**Comment by rafaelstevenson** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/67007111/115365423-93451a80-a1ee-11eb-958c-32198c2d27a1.png)

**Comment by haifeng-jin** [comment]
redirect to:
https://github.com/keras-team/keras-tuner/discussions/521
