### ISSUE TITLE
TensorBoard HParams plugin not working

### ISSUE THREAD

**Issue by sibyjackgrove** [keras-team/keras-tuner#427]
I was testing TensorBoard HParams plugin commit 3c7bff9d11ef697a144fb17237028aae9c840b51

I added the following callback `tf.keras.callbacks.TensorBoard(log_dir="./logs")` and passed it to `tuner.search()`

However, I am getting the following error when I try running tensorboard using `tensorboard --logdir logs
I am able to visualize scalars, graphs, and time series in tensorboard using the logs.
`
>  HParams error: Can't find an HParams-plugin experiment data in the log directory. Note that it takes some time to scan the log directory; if you just started Tensorboard it could be that we haven't finished scanning it yet. Consider trying again in a few seconds.

**Comment by carlthome** [comment]
My workaround for getting out HParams in TensorBoard via `tfk.callbacks.TensorBoard` involved two things:

1. https://github.com/keras-team/keras-tuner/pull/432
2. Making sure `kerastuner.Tuner.run_trial` is actually called, by circumventing the high-level tuners (unfortunately) because they have their `run_trial` call seemingly swallowed by a `MultiExecutionTuner`.

So for random search, the following seems to work together with 1.
```py
import kerastuner as kt

oracle = kt.tuners.randomsearch.RandomSearchOracle(objective="val_loss", max_trials=3)
tuner = kt.Tuner(oracle=oracle, hypermodel=build_model)
```
But an actual fix would be better because the above makes it hard to use `kt.Hyperband`, for example.

**Comment by sibyjackgrove** [comment]
@carlthome  Thanks for the fix. I will try it out.
