### ISSUE TITLE
hp.Int "max_value" not working as expected

### ISSUE THREAD

**Issue by rcmagic1** [keras-team/keras-tuner#59]
While using keras-tuner, the hp.Int "max_value" does not appear to be reached.  
E.g. I have the following but 'num_units' maxes-out at 96, not 128 as expected.
`    hp.Int('num_units',min_value=32,max_value=128,step=32)`
If I change to the following I can reach 128:
`        hp.Int('num_units',min_value=32,max_value=128+1,step=32)`

**Comment by rcmagic1** [comment]
Please disregard.  I see this comment now in "Int" function code suggested upper bound is excluded similar to Python "range" function:

`        max_value: Int. Upper limit of range (excluded).`

**Comment by omalleyt12** [comment]
@rcmagic1 could you submit a PR to update the README?

**Comment by gabrieldemarmiesse** [comment]
I believe that's a problem, as in proper english, the *maximum* of a given function is reached when the function take discreet values (exemple: `np.max`). I propose that since we haven't reached the 1.0, we consider changing the naming to follow conventions of signatures of existing python libs. A few examples:

### Python build-in range:

`range(start, stop[, step]) #stop not included`

### Python's random module:
`random.randrange(start, stop[, step]) # stop not included`

```python
random.randint(a, b)
#close to our signature (Int) but here the value returned is a <= N <= b
# The docs says: Alias for randrange(a, b+1). Our method does the contrary. Very confusing.
```

### Numpy:
`numpy.arange([start, ]stop, [step, ]dtype=None) #stop is exluded`
`numpy.random.randint(low[, high, size, dtype]) # high is excluded`
`numpy.random.random_integers(low, high=None, size=None) # high is included`

I propose that we follow the naming conventions of existing libs that are known by everyone and use `start`, `stop` and `step`. This way, we'll avoid confusion for many users.

**Comment by omalleyt12** [comment]
@gabrieldemarmiesse Agree this is an issue. I would kind of lean towards making `max_value` inclusive rather than changing the names, because the names are used by the internal and the Cloud service that we are going to integrate with. I think those services have `max_value` as inclusive too, but I'll have to check

Either way we should document better

**Comment by gabrieldemarmiesse** [comment]
I don't know how much work does this naming change represent (I imagine it's a lot), but I'd prefer to bite the bullet now than to go on forever with an API we're not satisfied with. Maybe @fchollet can give his opinion about it.

**Comment by omalleyt12** [comment]
Looked into this more, there were actually some inconsistencies b/t Oracles as to whether max_value was inclusive or exclusive. Ended up standardizing on inclusive, see PR: https://github.com/keras-team/keras-tuner/pull/116

**Comment by omalleyt12** [comment]
Also added note in the docstring to highlight this
